
$token = "eyJ0eXAiOiJKV1QiLCJub25jZSI6IlM1dVUwNHRvY3VWM05wdVpKQnJCXzlRc0ZLNGZXdzlfXzFyWk9fNE92UEkiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9lOTlmNjlkMi01OTQ2LTRiNDctOWNkMy00NzA2YTRhMDExODQvIiwiaWF0IjoxNjI4ODUzODMzLCJuYmYiOjE2Mjg4NTM4MzMsImV4cCI6MTYyODg1NzczMywiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFTUUEyLzhUQUFBQXZLVEsvK0JTUjZXWkpZQlZYS1NNSG9FdWIzKzZMY3JDQTJVY3MrejdBcFk9IiwiYW1yIjpbInB3ZCJdLCJhcHBfZGlzcGxheW5hbWUiOiJHcmFwaCBFeHBsb3JlciIsImFwcGlkIjoiZGU4YmM4YjUtZDlmOS00OGIxLWE4YWQtYjc0OGRhNzI1MDY0IiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJCaGFyZHdhaiIsImdpdmVuX25hbWUiOiJBbmt1ciIsImlkdHlwIjoidXNlciIsImlwYWRkciI6IjE2Ny4yMjAuMjU1LjEwMCIsIm5hbWUiOiJBbmt1ciBCaGFyZHdhaiIsIm9pZCI6ImMzYmM5NjhiLWU0YmQtNGUyYi05YThiLTA4OTUzZWRkYTg1OCIsInBsYXRmIjoiMyIsInB1aWQiOiIxMDAzMjAwMTU0QTc1Q0ZEIiwicmgiOiIwLkFXNEEwbW1mNlVaWlIwdWMwMGNHcEtBUmhMWElpOTc1MmJGSXFLMjNTTnB5VUdSdUFBay4iLCJzY3AiOiJDYWxlbmRhcnMuUmVhZCBDYWxlbmRhcnMuUmVhZC5TaGFyZWQgQ2FsZW5kYXJzLlJlYWRXcml0ZSBDYWxlbmRhcnMuUmVhZFdyaXRlLlNoYXJlZCBNYWlsLlJlYWQgTWFpbC5SZWFkLlNoYXJlZCBNYWlsLlJlYWRCYXNpYyBNYWlsLlJlYWRXcml0ZSBNYWlsLlJlYWRXcml0ZS5TaGFyZWQgTWFpbC5TZW5kIE1haWwuU2VuZC5TaGFyZWQgb3BlbmlkIHByb2ZpbGUgVXNlci5SZWFkIFVzZXJBdXRoZW50aWNhdGlvbk1ldGhvZC5SZWFkIFVzZXJBdXRoZW50aWNhdGlvbk1ldGhvZC5SZWFkLkFsbCBVc2VyQXV0aGVudGljYXRpb25NZXRob2QuUmVhZFdyaXRlIFVzZXJBdXRoZW50aWNhdGlvbk1ldGhvZC5SZWFkV3JpdGUuQWxsIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoiNERURmptaWxhUjl0b1lYN2NlWUpJc0sxX2I4TjdFT1BLNUszQWlLRWdRYyIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJOQSIsInRpZCI6ImU5OWY2OWQyLTU5NDYtNGI0Ny05Y2QzLTQ3MDZhNGEwMTE4NCIsInVuaXF1ZV9uYW1lIjoiYW5rdXIuYmhhcmR3YWpATTM2NXgzOTkxMjQub25taWNyb3NvZnQuY29tIiwidXBuIjoiYW5rdXIuYmhhcmR3YWpATTM2NXgzOTkxMjQub25taWNyb3NvZnQuY29tIiwidXRpIjoia1hJZFpBcWtqVWk5STE5aUVlZUVBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiNjJlOTAzOTQtNjlmNS00MjM3LTkxOTAtMDEyMTc3MTQ1ZTEwIiwiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19zdCI6eyJzdWIiOiJHVUl4V09kUTVrdkhCSEpGY0tkYkpsY1Awb1pTNjlXaS1hRDRRckRKTlBBIn0sInhtc190Y2R0IjoxNTk5MDgyMjg1fQ.PGg85PdLBAhEwZKKHjdqyOuRMVwoiZ2twZCuWuTQHP3mnhb58zDZVlEDLfjYToQTSx9882S_toO1hSMT_Kf3DCIHrxB2f8i7ja4O8_igvzSg3KmwKcgsLihEr10Mt0Qe_a7Xg7_mxJ3hxyUdkSNOnnEEBydKfS9V0rmODn6SYDfsO1zfvck45UKUxUIi_Npt3wICwSl6qojG2THV9wSpl6rq6JvvsouUSjWj3QcAkmXgZ7tdIvqAq8zkDtD5vav7BtCy75m0_9GKVGS5tL2wvSjWVcTT4diGCTACanSeaJGGNm7-aSOnWvt5B82yXsD1lkV2CAXBZb9598RMh8PgUQ"
$uriGet = "https://graph.microsoft.com/v1.0/me/events?$select=subject, id"
$uriDelete = "https://graph.microsoft.com/v1.0/me/events/"
$counter = 0

$calendarItem = Invoke-RestMethod -Uri $uriGet -Method Get -Headers @{"Authorization"="Bearer $token"}
Write-Host ""
Write-Host "Preparing to delete all meetings in calendar..." -f Yellow

foreach ($item in $calendarItem)
{
    Write-Warning "Deleting following meetings..."
    Write-Host ""
    Write-Output $item.value.subject
    Write-Host ""

    foreach ($id in $item.value.id)
    {
        Invoke-RestMethod -Uri ($uriDelete + $id) -Method Delete -Headers @{"Authorization"="Bearer $token"}
        $counter++
    }
}
Write-Host "Script has finished deleting all meetings in calendar." -f Green
Write-Host "Total items removed:$counter" -f Green
